### ISSUE TITLE
suggestion -- improve use of USB media

### ISSUE THREAD

**Issue by SaintDanbert** [jsamr/bootiso#17]
Please consider the following features that might improve the use of USB media.

1.  Accept a **--label <string>** option and set that label at the end of the 'dd' processing.
For my part, I use meaningful labels so that I can keep an index of the content that is on the various USB media devices that I have.

2.  Create a "distro space" and a "data space" on the bootable USB media device.
Given that USB media devices are now available with much more capactity than is required even the largest distribution, it might be nice to have an end-user "data space" on the device in addition to the "distribution space."  I realize that not all USB media will support multiple partitions, but bootiso could detect this and report if this option cannot be implemented.

**Comment by jsamr** [comment]
Hi @SaintDanbert 
Thanks for your participation.

1.  `--label` option [already exists](https://github.com/jsamr/bootiso#options) but only works for mount-rsync mode (and not dd indeed).
So you would like to have it available for `dd` mode ? There is some work, since some ISO image files contain multiple partitions&star;. So I have to identify the right partition first with some heuristics (the biggest? the non-ESP one?)
2. This is feature request #1. I will definitely implement this in a near future :-)

&star; See for example the output of `fdisk -l manjaro-architect-17.1.11-stable-x86_64.iso`. You'll see an ESP (EFI System Partition) at second position.
```
Dsk manjaro-architect-17.1.11-stable-x86_64.iso: 527.4 MiB, 552970240 bytes, 1080020 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device                                       Boot   Start     End Sectors   Size Id Type
manjaro-architect-17.1.11-stable-x86_64.iso1 *         64 1071827 1071764 523.3M cd unknown
manjaro-architect-17.1.11-stable-x86_64.iso2      1071828 1080019    8192     4M ef EFI (FAT-12/16/32)

```

**Comment by jsamr** [comment]
Closing now. Feel free to open a ticket for `--label` to work with dd-mode :-)
